<?php
/**
 * Description: this file contains ACF fields settings for Certificate mails
 * Groups: 'group_cert1', 'group_cert2',
 * Fields:
 *      'General settings for creating Course Certificate mails':
 *                                                                      group key 'group_cert1'
 *              Mail Subject:                                               key 'field_cert11',     name 'subject',
 *              Blind carbon copy email:                                    key 'field_cert12',     name 'bcc_text',
 *              From (address):                                             key 'field_cert13',     name 'from_address',
 *              From (name):                                                key 'field_cert14',     name 'from_name',
 *              Default mail message:                                       key 'field_cert15',     name 'default_message',
 *              Default Certificate Image:                                  key 'field_cert16',     name 'default_attachment',
 *
 *      'Add settings to specific Course Certificate mail letter'
 *                                                                      group key 'group_cert2',
 *              Specific Certificate Email Settings:                        key 'field_cert21',     name 'spec_set',
 *              Course:                                                     key 'field_cert22',     name 'course',
 *              Mail Subject:                                               key  'field_cert23',    name 'spec_subject',
 *              Blind carbon copy email:                                    key 'field_cert24',     name 'spec_bcc_text',
 *              From (address):                                             key 'field_cert25',     name 'spec_from_address',
 *              From (name):                                                key 'field_cert26',     name 'spec_from_name',
 *              Mail message:                                               key 'field_cert27',     name 'message',
 *              Certificate Image:                                          key 'field_cert28',     name 'attachment',
 */
add_action('acf/init', 'register_certificate_fields_settings');
function register_certificate_fields_settings() {
    if( function_exists('acf_add_local_field_group') ):
        // general mail settings
        $fields_certificates_general = array(
            array(
                'key' => 'field_cert11',
                'label' => 'Mail Subject',
                'name' => 'subject',
                'type' => 'text',
                'prefix' => '',
                'instructions' => '',
                'placeholder' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => __('Certificate Luxe Academy', "luxeacademy"),
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array(
                'key' => 'field_cert12',
                'label' => 'Blind carbon copy email',
                'name' => 'bcc_text',
                'type' => 'email',
                'prefix' => '',
                'instructions' => '',
                'placeholder' => 'some_admin@gmail.com',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array(
                'key' => 'field_cert13',
                'label' => 'From (address)',
                'name' => 'from_address',
                'type' => 'text',
                'prefix' => '',
                'instructions' => '',
                'placeholder' => get_home_url(),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => get_home_url(),
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array(
                'key' => 'field_cert14',
                'label' => 'From (name)',
                'name' => 'from_name',
                'type' => 'text',
                'prefix' => '',
                'instructions' => '',
                'placeholder' =>  get_bloginfo('name').' team',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' =>  get_bloginfo('name').' team',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array(
                'key' => 'field_cert15',
                'label' => 'Default mail message',
                'name' => 'default_message',
                'type' => 'wysiwyg',
                'prefix' => '',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => "<strong>Congratulations!</strong><br/>You finished the Course. Here is your Certificate!<br/><br/><em>Best regards, the <a href='".get_home_url()."'>".get_bloginfo('name')."</a> team.</em>",
                'placeholder' => 'please write congratulation mail content here',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array(
                'key' => 'field_cert16',
                'label' => 'Default Certificate Image',
                'name' => 'default_attachment',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'full',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            )
        );
        acf_add_local_field_group(
            array(
                'key' => 'group_cert1',
                'title' => 'General settings for creating Course Certificate mails',
                'fields' => $fields_certificates_general,
                'location' => array (
                    array (
                        array (
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'theme-certificates-settings',
                        ),
                    ),
                ),
                'menu_order' => 0,
            )
        );
        // for every specific Course on site
        $fields_certificate_settings = array(
            array (
                'key' => 'field_cert21',
                'label' => 'Specific Certificate Email Settings',
                'name' => 'spec_set',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'min' => '',
                'max' => '',
                'layout' => 'row',
                'button_label' => 'Add Certificate Email type',
                'sub_fields' => array (
                    array (
                        'key' => 'field_cert22',
                        'label' => 'Course',
                        'name' => 'course',
                        'type' => 'post_object',
                        'post_type' => 'product',
                        'taxonomy' => '',
                        'allow_null' => 0,
                        'multiple' => false,
                        'return_format' => 'id',
                        'prefix' => '',
                        'instructions' => 'Default Certificate Settings',
                        'placeholder' => 'choose Course Name here',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array(
                        'key' => 'field_cert23',
                        'label' => 'Mail Subject',
                        'name' => 'spec_subject',
                        'type' => 'text',
                        'prefix' => '',
                        'instructions' => '',
                        'placeholder' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => "",
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array(
                        'key' => 'field_cert24',
                        'label' => 'Blind carbon copy email',
                        'name' => 'spec_bcc_text',
                        'type' => 'email',
                        'prefix' => '',
                        'instructions' => '',
                        'placeholder' => 'some_admin@gmail.com',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array(
                        'key' => 'field_cert25',
                        'label' => 'From (address)',
                        'name' => 'spec_from_address',
                        'type' => 'text',
                        'prefix' => '',
                        'instructions' => '',
                        'placeholder' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array(
                        'key' => 'field_cert26',
                        'label' => 'From (name)',
                        'name' => 'spec_from_name',
                        'type' => 'text',
                        'prefix' => '',
                        'instructions' => '',
                        'placeholder' =>  '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array(
                        'key' => 'field_cert27',
                        'label' => 'Mail message',
                        'name' => 'message',
                        'type' => 'wysiwyg',
                        'prefix' => '',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => "",
                        'placeholder' => 'please write congratulation mail content here',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array(
                        'key' => 'field_cert28',
                        'label' => 'Certificate Image',
                        'name' => 'attachment',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'full',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                ),
            ),
        );
        acf_add_local_field_group(
            array(
                'key' => 'group_cert2',
                'title' => 'Add settings to specific Course Certificate mail letter',
                'fields' => $fields_certificate_settings,
                'location' => array (
                    array (
                        array (
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'theme-certificates-settings',
                        ),
                    ),
                ),
                'menu_order' => 1,
            )
        );
    endif;
}