<?php
/**
 * Description: this file contain ACF fields settings for Users
 * Groups: 'group_user1', 'group_user2',
 * Fields:
 *                  group name 'group_user1'
 *      Avatar:     key 'field_user1',  name 'user_avatar'
 *
 * group name 'group_user2'
 *
 *
 */
add_action('acf/init', 'register_acf_fields_user_settings');
function register_acf_fields_user_settings() {
    if( function_exists('acf_add_local_field_group') ):
        // add capability to add user avatar
        $fields_user = array (
            array (
                'key' => 'field_user1',
                'label' => 'Avatar',
                'name' => 'user_avatar',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'full',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        );
        acf_add_local_field_group(array(
            'key' => 'group_user1',
            'title' => 'User avatar',
            'fields' => $fields_user,
            'location' => array (
                array (
                    array (
                        'param' => 'user_form',
                        'operator' => '==',
                        'value' => 'edit',
                    ),
                ),
            ),
        ));
        // add special information settings for user role Teacher
        $fields_teacher = array(
            array(
                'key' => 'field_teach1',
                'label' => 'Specialty',
                'name' => 'specialty',
                'type' => 'select',
                'prefix' => '',
                'instructions' => "please choose the Teacher's specialty",
                'choices' => array(
                    'coding' => 'Coding',
                    'design' => 'Design',
                ),
                'multiple' => 0,
                'allow_null' => 0,
                'placeholder' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array(
                'key' => 'field_teach2',
                'label' => 'Instructor Credentials',
                'name' => 'array_credentials',
                'type' => 'repeater',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => '',
                'max' => '4',
                'layout' => 'row',
                'button_label' => 'Add Credential',
                'sub_fields' => array(
                    array(
                        'key' => 'field_teach3',
                        'label' => 'Recommendation',
                        'name' => 'credential',
                        'type' => 'group',
                        'prefix' => '',
                        'instructions' => "Please write here some sentences about the Teacher's credentials. You can add recommendation author name, avatar and profession.",
                        'placeholder' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                        'button_label' => 'Add Component',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_teach4',
                                'label' => 'Recommendation text',
                                'name' => 'credential_content',
                                'type' => 'wysiwyg',
                                'prefix' => '',
                                'instructions' => '',
                                'placeholder' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array(
                                'key' => 'field_teach5',
                                'label' => 'Recommendation author',
                                'name' => 'credential_author',
                                'type' => 'text',
                                'prefix' => '',
                                'instructions' => '',
                                'placeholder' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array(
                                'key' => 'field_teach6',
                                'label' => 'Recommendation author profession',
                                'name' => 'credential_author_profession',
                                'type' => 'text',
                                'prefix' => '',
                                'instructions' => '',
                                'placeholder' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array(
                                'key' => 'field_teach7',
                                'label' => 'Recommendation author Avatar',
                                'name' => 'credential_author_avatar',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'preview_size' => 'full',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_teach31',
                'label' => 'Instructor social links',
                'name' => 'array_soc_links',
                'type' => 'repeater',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => '',
                'max' => '4',
                'layout' => 'table',
                'button_label' => 'Add Social Links',
                'sub_fields' => array(
                    array (
                        'key' => 'field_contact311',
                        'label' => 'Link URL',
                        'name' => 'link_url',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                    ),
                    array (
                        'key' => 'field_contact312',
                        'label' => 'Link Icon',
                        'name' => 'link_icon',
                        'type' => 'select',
                        'prefix' => '',
                        'instructions' => "please choose right icon",
                        'choices' => array(
                            'fa-facebook' => 'facebook',
                            'fa-instagram' => 'instagram',
                            'fa-twitter' => 'twitter',
                            'fa-pinterest>' => 'pinterest',
                        ),
                        'multiple' => 0,
                        'allow_null' => 0,
                        'placeholder' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                )
            )
        );
        acf_add_local_field_group(array(
            'key' => 'group_user2',
            'title' => 'Teacher information',
            'fields' =>  $fields_teacher,
            'location' => array (
                array (
                    array (
                        'param' => 'user_role',
                        'operator' => '==',
                        'value' => 'teacher',
//                        'value' => 'teaches',
                    ),
                ),
            ),
        ));
        // add special information settings for user role Customer
        $fields_customer = array(
            array(
                'key' => 'field_us_pr',
                'label' => 'User Progress',
                'name' => 'user_progress',
                'type' => 'repeater',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => '',
                'max' => '',
                'layout' => 'row',
                'button_label' => 'Add course Progress',
                'sub_fields' => array(
                    array (
                        'key' => 'field_us1',
                        'label' => 'Course name',
                        'name' => 'course_id',
                        'type' => 'post_object',
                        'post_type' => 'product',
                        'taxonomy' => '',
                        'allow_null' => 0,
                        'multiple' => false,
                        'return_format' => 'id',
                        'prefix' => '',
                        'instructions' => '',
                        'placeholder' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array (
                        'key' => 'field_us2',
                        'label' => 'Course certificate obtained',
                        'name' => 'certificate_given',
                        'type' => 'true_false',
                        'layout' => 'horizontal',
                        'message' => 'user has the Certificate for this Course',
                        'prefix' => '',
                        'instructions' => '',
                        'placeholder' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => false,
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array(
                        'key' => 'field_us_pr1',
                        'label' => 'Course Progress',
                        'name' => 'array_course_pr',
                        'type' => 'repeater',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => '',
                        'max' => '',
                        'layout' => 'table',
                        'button_label' => 'Add Lessons Progress',
                        'sub_fields' => array(
                            array (
                                'key' => 'field_us_pr11',
                                'label' => 'Section name',
                                'name' => 'sec_name',
                                'type' => 'text',
                                'prefix' => '',
                                'instructions' => '',
                                'placeholder' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_us_pr12',
                                'label' => 'Lesson name',
                                'name' => 'les_name',
                                'type' => 'text',
                                'prefix' => '',
                                'instructions' => '',
                                'placeholder' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_us_pr13',
                                'label' => 'Done',
                                'name' => 'done',
                                'type' => 'true_false',
                                'layout' => 'horizontal',
                                'message' => 'user done the lesson',
                                'prefix' => '',
                                'instructions' => '',
                                'placeholder' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => false,
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                        )
                    ),
                ),
            ),
        );
        acf_add_local_field_group(array(
            'key' => 'group_user3',
            'title' => 'Learning progress',
            'fields' =>  $fields_customer,
            'location' => array (
                array (
                    array (
                        'param' => 'user_role',
                        'operator' => '==',
                        'value' => 'customer',
                    ),
                ),
            ),
        ));
    endif;
}